apiVersion: v1
kind: Namespace
metadata:
  name: darwin-infra
  labels:
    name: darwin-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: darwin
  labels:
    name: darwin

---
apiVersion: v1
kind: Namespace
metadata:
  name: darwin-target
  labels:
    name: darwin-target
